# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LgJikK5zyk7UXIcZWiXGi7wdcaWorSOG
"""

s='bhagyasri annapurna '
print(s.split('h'))
print(s.capitalize())
print(s.title())
print(s.strip())
print(s.upper())
print(s.center(30,'3'))
print(s.isspace())
print(s.startswith('b'))
print(s.startswith('f'))
b=' '
print(b.isspace())
s='2abc'
print(s.isdigit())
print(s.isalnum())
print(s.isalpha())

s='bhagya sri'
print(s[:4])
print(s[2:])
print(s[-1:])
print(s[-8:-1])
print(s[-1:-8])
print(s[::])
print(s[1:10:2])
print(s[-1:-10:-3])
print(s[-10:-1:2])
print(s[1:5:1])
print(s[::-1])