# -*- coding: utf-8 -*-
"""Assg1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bP8KAREtePn3jBOsKFOs64Sy47qkf5pr
"""

s='this is My First Python programming class and i am learNING python string and its function'
print(s[1:300:3])
print(s[::-1])
b=s.upper()
print(b)
print(s.split(b))
print(s.lower())
print(s.capitalize())
#isalpha() gives true if given string consists only alphabets and isalnum() gives true if given string contains alphabets or numerics or both.
print(s.isalpha())
print(s.isalnum())
#The expandtabs() method sets the tab size to the specified number of whitespaces.
t='b\th\ta\tg\ty\ta'
print(t.expandtabs(1))
print(t.expandtabs(2))
print(t.expandtabs(3))
print(t.expandtabs(4))
print(t.expandtabs(5))
print(t.expandtabs(6))
a=' bhagyasri '
print(a.strip())
print(a.lstrip())
print(a.rstrip())
s='Anil ganesh'
print(s.replace('ganesh','bhagya'))
#string center() method will center align the string, using a specified character(that we give)and space is default, as the fill character.
s='Anil'
print(s.center(10,'t'))
s=13
print(s)
#compiler means it checks the whole program at once and interpreter will check program line by line
#python is an interpreted language, as per my understanding the code is compiled line by line . if we take above code i have used s for several times 
#everytime it has different value(string and integer) assigned to it so if it is compiler language then it many arise error as it doesn't understand 
#whether it has to consider s as string or integer but it doesn't arose any error as it compiles line by line it takes s as string when it compiles that 
#particular line and when it goes to next line it takes new variables s which stores an interger value'''